#!/usr/bin/env python3
"""GEWUM laptop minimal working example (MWE).

Runs the real RD workflow - structure generation, database build, diversity
selection, uMLIP relaxation, energy post-processing and convex-hull
stability screening - using ONLY the installed GEWUM Python package.
No SLURM, no copied shell scripts: every step calls the same
`python -m gewum.src.*` entry points that the HPC shell scripts invoke,
so the laptop run and the HPC run exercise identical code paths.

The structure inputs come from the real cifgen pipeline: this folder's
cifgen.inp (Mg-Sn compositions, 20 structures per space group each) is fed
to `python -m gewum.src.RDworkflows.cif_generate`, which walks ALL space
groups (2-230) exactly like a production cifgen run. The diversity-
selection step then keeps 2 structures per SG (--target 2), and the
survivors are relaxed with the uMLIP potential. Elemental references
(Mg, Sn) are generated by the same pipeline (single-element compositions
in cifgen.inp) and relaxed identically, so the whole hull is
uMLIP-consistent and the example needs no Materials Project data and no
network access.

Runtime: dominated by the uMLIP relaxations (with all space groups this
can be hours on a laptop - shrink cifgen.inp's max_xtals for a quick demo).
Dependencies: `pip install -e ".[ml]"` (GEWUM + mattersim), pymatgen, numpy.

Usage:
    mkdir mwe && cd mwe
    python run_laptop_mwe.py
"""

import argparse
import os
import subprocess
import sys
import time

# --------------------------------------------------------------------------
# Step 0: dependency check
# --------------------------------------------------------------------------


def check_dependencies():
    import importlib.util

    missing = []
    for name in ("gewum", "pymatgen", "mattersim"):
        if importlib.util.find_spec(name) is None:
            missing.append(name)
    if missing:
        sys.exit(
            "[ERROR] Missing packages: "
            + ", ".join(missing)
            + "\n  Install GEWUM with: pip install -e '.[ml]'"
        )


# --------------------------------------------------------------------------
# Step 1: inputs - real cifgen pipeline (cifgen.inp -> cif_generate.py)
# --------------------------------------------------------------------------


def build_inputs(workdir, ncpu):
    """Run the production structure generator on this folder's cifgen.inp.

    Identical to `gewum RD --mode cifgen` + cifgen.sh: reads cifgen.inp,
    generates random structures per composition per space group with
    pyxtal, and stores them as CIF rows in <formula>/structures.db
    (stage='initial'). Single-element compositions in cifgen.inp (Mg, Sn)
    serve as elemental references for the hull. A pre-existing non-empty
    DB is left untouched so a re-run resumes rather than recomputes.
    """
    # Skip generation when a previous run already populated the databases
    # (resume semantics; delete the working dir to regenerate from scratch).
    from gewum.src.common.cif_db import CifDatabase

    def _has_rows(db_dir):
        with CifDatabase(db_dir) as db:
            return db.count() > 0

    populated = [d for d in sorted(os.listdir(workdir))
                 if os.path.isfile(os.path.join(workdir, d, "structures.db"))]
    if any(_has_rows(os.path.join(workdir, d)) for d in populated):
        print(f"[inputs] {len(populated)} formula DB(s) already populated; "
              "skipping cifgen (delete the working dir to regenerate)")
        return

    # cifgen.inp lives next to this script; copy it into the working dir so
    # the working dir stays self-contained, exactly like a submitted cifgen
    # job reads cifgen.inp from its own directory. No-op when the working
    # dir IS the script dir (workdir="."): reading and writing the same
    # path in one expression would truncate the file before reading it.
    src_inp = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "cifgen.inp")
    dst_inp = os.path.join(workdir, "cifgen.inp")
    if os.path.abspath(src_inp) == os.path.abspath(dst_inp):
        print(f"[inputs] cifgen.inp already in place ({src_inp})")
    else:
        with open(src_inp, encoding="utf-8") as fh:
            content = fh.read()
        with open(dst_inp, "w", encoding="utf-8") as out:
            out.write(content)
        print(f"[inputs] copied cifgen.inp -> {dst_inp}")

    step(
        ["-m", "gewum.src.RDworkflows.cif_generate",
         "--dim", "3",
         "--input-file", "cifgen.inp",
         "--max-atoms", "12",        # keep cells small: default is 36
         "--max-attempts", "20"],
        cwd=workdir, label="cifgen", log=os.path.join(workdir, "cifgen.out"),
        env={**os.environ, "SLURM_CPUS_PER_TASK": str(ncpu)},
    )


# --------------------------------------------------------------------------
# Step 2: diversity selection (medoid, keeps 2 of 20 per SG)
# --------------------------------------------------------------------------


def run_selection(workdir, workers):
    step(
        [
            "-m", "gewum.src.common.selection.structure_select",
            "--dim", "3d",
            "--method", "medoid",
            "--target", "2",           # keep 2 of the 20 structures per SG
            "--input-dir", workdir,
            "--workers", str(workers),
            "--descriptor", "simple",
        ],
        cwd=workdir,
        label="select",
    )


# --------------------------------------------------------------------------
# Step 3: uMLIP relaxation (DB mode, identical to relax_umlip.sh)
# --------------------------------------------------------------------------


def run_relaxation(workdir, fmax, max_steps):
    from gewum.src.common.cif_db import CifDatabase

    formulas = [d for d in sorted(os.listdir(workdir))
                if os.path.isfile(os.path.join(workdir, d, "structures.db"))]
    if not formulas:
        sys.exit("[ERROR] no formula directories with structures.db found")

    for formula in formulas:
        fdir = os.path.join(workdir, formula)
        db_path = os.path.join(fdir, "structures.db")
        tmp_dir = os.path.join(fdir, ".relax_tmp")
        csv_path = os.path.join(fdir, "energy_results.csv")
        log_path = os.path.join(workdir, "cif_relax.out")

        with CifDatabase(fdir) as db:
            tasks = list(db.query_initial_tasks())
        print(f"[relax] {formula}: {len(tasks)} initial task(s)")

        for sg, name, _content in tasks:
            step(
                [
                    "-m", "gewum.src.common.relaxation.relax_db_io",
                    "worker",
                    "--db", db_path,
                    "--sg", str(sg),
                    "--name", name,
                    "--tmp-dir", tmp_dir,
                    "--mode", "2",           # atoms + cell
                    "--fmax", str(fmax),
                    "--max-steps", str(max_steps),
                ],
                cwd=workdir, label=f"relax {formula}/{sg}/{name}",
                log=log_path,
            )

        step(
            [
                "-m", "gewum.src.common.relaxation.relax_db_io",
                "commit",
                "--db", db_path,
                "--tmp-dir", tmp_dir,
                "--csv", csv_path,
                "--cleanup",
            ],
            cwd=workdir, label=f"commit {formula}", log=log_path,
        )


# --------------------------------------------------------------------------
# Step 4: post-processing (bond check + energy ranking), like post_relax.sh
# --------------------------------------------------------------------------


def run_postprocessing(workdir, gap=0.001, max_n=5, bond_threshold=1.0):
    formulas = [d for d in sorted(os.listdir(workdir))
                if os.path.isfile(os.path.join(workdir, d, "structures.db"))]

    for formula in formulas:
        fdir = os.path.join(workdir, formula)
        step(
            [
                "-m", "gewum.src.common.postprocess.bond_check",
                "--threshold", str(bond_threshold),
                "--base-dir", fdir,
            ],
            cwd=workdir, label=f"bond check {formula}",
        )
        step(
            ["-m", "gewum.src.RDworkflows.energy_post",
             "--gap", str(gap), "--max-n", str(max_n)],
            cwd=fdir, label=f"energy post {formula}",
        )

    # Aggregate per-formula selections into 0_final_result_tot.txt
    # (same header/rows as post_relax.sh).
    header = ("Chemical_Formula,CIF_Base_Name,Total_Energy_eV,"
              "Energy_per_Atom_eV,Relaxed_CIF_Path,SG_ori")
    tot_path = os.path.join(workdir, "0_final_result_tot.txt")
    with open(tot_path, "w", encoding="utf-8") as out:
        out.write(header + "\n")
        for formula in formulas:
            sel = os.path.join(workdir, formula, "0_final_results.txt")
            if not os.path.isfile(sel):
                continue
            with open(sel, encoding="utf-8") as fh:
                for line in fh.readlines()[1:]:
                    out.write(line)
    print(f"[post] {tot_path} written")


# --------------------------------------------------------------------------
# Step 5: convex-hull stability (self-hull, fully offline)
# --------------------------------------------------------------------------


def run_ehull(workdir):
    step(
        [
            "-m", "gewum.src.common.ehull.Ehull_compatibility",
            "--input", os.path.join(workdir, "0_final_result_tot.txt"),
            "--output", os.path.join(workdir, "Hull_result.csv"),
            "--self-hull",
            # Elemental references come from the single-element input rows
            # (Mg, Sn generated by cifgen); the placeholder key satisfies
            # the production CLI's unconditional api-key/mp-data check.
            "--api-key", "offline",
        ],
        cwd=workdir, label="Ehull (self-hull)",
    )


# --------------------------------------------------------------------------
# Step 6: summary
# --------------------------------------------------------------------------


def show_results(workdir):
    print("\n" + "=" * 72)
    print("RESULT SUMMARY")
    print("=" * 72)

    hull = os.path.join(workdir, "Hull_result.csv")
    if os.path.isfile(hull):
        with open(hull, encoding="utf-8") as fh:
            rows = list(csv_reader(fh))
        if rows:
            head = rows[0]
            idx_f = [i for i, h in enumerate(head) if "formula" in h.lower()]
            idx_e = [i for i, h in enumerate(head)
                     if "e_above_hull" in h.lower() or "formation" in h.lower()]
            print(f"{'formula':<12} {'e_above_hull (eV/atom)':>22}")
            for r in rows[1:]:
                f_ = r[idx_f[0]] if idx_f else ""
                e_ = r[idx_e[0]] if idx_e else ""
                print(f"{f_:<12} {e_:>22}")
            print(f"\nFull table: {hull}")
    else:
        print("[summary] Hull_result.csv not found")


def csv_reader(fh):
    import csv
    return csv.reader(fh)


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def step(argv, cwd, label, log=None, env=None):
    """Run one `python -m ...` step; fail loudly with the step name."""
    cmd = [sys.executable] + argv
    print(f"\n[{label}] $ {' '.join(cmd)}  (cwd: {cwd})")
    t0 = time.time()
    stdout = open(log, "a", encoding="utf-8") if log else None
    try:
        result = subprocess.run(cmd, cwd=cwd, stdout=stdout,
                                stderr=subprocess.STDOUT, env=env)
    except OSError as exc:
        sys.exit(f"[ERROR] step '{label}' could not start: {exc}")
    finally:
        if stdout:
            stdout.close()
    dt = time.time() - t0
    if result.returncode != 0:
        sys.exit(f"[ERROR] step '{label}' failed (exit {result.returncode}); "
                 f"see {log if log else 'output above'}")
    print(f"[{label}] done in {dt:.1f}s")


def main():
    parser = argparse.ArgumentParser(
        description="GEWUM laptop minimal working example (RD workflow, no SLURM)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--workdir", default=".",
                        help="working directory (formula dirs are created here)")
    parser.add_argument("--fmax", type=float, default=0.05,
                        help="force convergence threshold (eV/A)")
    parser.add_argument("--max-steps", type=int, default=50,
                        help="maximum relaxation steps per structure")
    parser.add_argument("--ncpu", type=int, default=1,
                        help="worker processes/threads for cifgen and selection "
                             "(default 1 = single core; relaxation stays serial)")
    parser.add_argument("--skip-select", action="store_true",
                        help="skip the diversity-selection step")
    parser.add_argument("--skip-ehull", action="store_true",
                        help="skip the convex-hull step (saves element relaxations)")
    args = parser.parse_args()

    t0 = time.time()
    check_dependencies()

    # Cap BLAS/torch thread pools (inherited by every subprocess); workers
    # for cifgen/selection come from --ncpu below.
    os.environ["OMP_NUM_THREADS"] = str(args.ncpu)
    os.environ["MKL_NUM_THREADS"] = str(args.ncpu)

    workdir = os.path.abspath(args.workdir)
    os.makedirs(workdir, exist_ok=True)
    os.chdir(workdir)

    build_inputs(workdir, args.ncpu)

    if not args.skip_select:
        run_selection(workdir, args.ncpu)

    run_relaxation(workdir, args.fmax, args.max_steps)
    run_postprocessing(workdir)

    if not args.skip_ehull:
        run_ehull(workdir)

    show_results(workdir)
    print(f"\nTotal runtime: {time.time() - t0:.1f}s")
    print("Done. Outputs: energy_final.txt, 0_final_result_tot.txt, "
          "Hull_result.csv per the working directory.")


if __name__ == "__main__":
    main()
